package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * CaracteristicasdinoId generated by hbm2java
 */
public class CaracteristicasdinoId  implements java.io.Serializable {


     private int iddino;
     private int id;

    public CaracteristicasdinoId() {
    }

    public CaracteristicasdinoId(int iddino, int id) {
       this.iddino = iddino;
       this.id = id;
    }
   
    public int getIddino() {
        return this.iddino;
    }
    
    public void setIddino(int iddino) {
        this.iddino = iddino;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaracteristicasdinoId) ) return false;
		 CaracteristicasdinoId castOther = ( CaracteristicasdinoId ) other; 
         
		 return (this.getIddino()==castOther.getIddino())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIddino();
         result = 37 * result + this.getId();
         return result;
   }   


}


