package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Correoescuela generated by hbm2java
 */
public class Correoescuela  implements java.io.Serializable {


     private CorreoescuelaId id;
     private Escuela escuela;

    public Correoescuela() {
    }

    public Correoescuela(CorreoescuelaId id, Escuela escuela) {
       this.id = id;
       this.escuela = escuela;
    }
   
    public CorreoescuelaId getId() {
        return this.id;
    }
    
    public void setId(CorreoescuelaId id) {
        this.id = id;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }




}


