package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Correosparque generated by hbm2java
 */
public class Correosparque  implements java.io.Serializable {


     private CorreosparqueId id;
     private Parque parque;

    public Correosparque() {
    }

    public Correosparque(CorreosparqueId id, Parque parque) {
       this.id = id;
       this.parque = parque;
    }
   
    public CorreosparqueId getId() {
        return this.id;
    }
    
    public void setId(CorreosparqueId id) {
        this.id = id;
    }
    public Parque getParque() {
        return this.parque;
    }
    
    public void setParque(Parque parque) {
        this.parque = parque;
    }




}


