package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Telescuela generated by hbm2java
 */
public class Telescuela  implements java.io.Serializable {


     private TelescuelaId id;
     private Escuela escuela;

    public Telescuela() {
    }

    public Telescuela(TelescuelaId id, Escuela escuela) {
       this.id = id;
       this.escuela = escuela;
    }
   
    public TelescuelaId getId() {
        return this.id;
    }
    
    public void setId(TelescuelaId id) {
        this.id = id;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }




}


