package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Telefonosempleado generated by hbm2java
 */
public class Telefonosempleado  implements java.io.Serializable {


     private TelefonosempleadoId id;
     private Empleado empleado;

    public Telefonosempleado() {
    }

    public Telefonosempleado(TelefonosempleadoId id, Empleado empleado) {
       this.id = id;
       this.empleado = empleado;
    }
   
    public TelefonosempleadoId getId() {
        return this.id;
    }
    
    public void setId(TelefonosempleadoId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


