package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Telefonosparque generated by hbm2java
 */
public class Telefonosparque  implements java.io.Serializable {


     private TelefonosparqueId id;
     private Parque parque;

    public Telefonosparque() {
    }

    public Telefonosparque(TelefonosparqueId id, Parque parque) {
       this.id = id;
       this.parque = parque;
    }
   
    public TelefonosparqueId getId() {
        return this.id;
    }
    
    public void setId(TelefonosparqueId id) {
        this.id = id;
    }
    public Parque getParque() {
        return this.parque;
    }
    
    public void setParque(Parque parque) {
        this.parque = parque;
    }




}


