package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipovisita generated by hbm2java
 */
public class Tipovisita  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);

    public Tipovisita() {
    }

	
    public Tipovisita(int id) {
        this.id = id;
    }
    public Tipovisita(int id, String descripcion, Set<Reservacion> reservacions) {
       this.id = id;
       this.descripcion = descripcion;
       this.reservacions = reservacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }
    
    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }




}


