package dominio;
// Generated 09-jun-2014 20:30:13 by Hibernate Tools 3.6.0



/**
 * Trabajar generated by hbm2java
 */
public class Trabajar  implements java.io.Serializable {


     private TrabajarId id;
     private Empleado empleado;
     private Parque parque;
     private Double sueldo;
     private String diadescanso;

    public Trabajar() {
    }

	
    public Trabajar(TrabajarId id, Empleado empleado, Parque parque) {
        this.id = id;
        this.empleado = empleado;
        this.parque = parque;
    }
    public Trabajar(TrabajarId id, Empleado empleado, Parque parque, Double sueldo, String diadescanso) {
       this.id = id;
       this.empleado = empleado;
       this.parque = parque;
       this.sueldo = sueldo;
       this.diadescanso = diadescanso;
    }
   
    public TrabajarId getId() {
        return this.id;
    }
    
    public void setId(TrabajarId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Parque getParque() {
        return this.parque;
    }
    
    public void setParque(Parque parque) {
        this.parque = parque;
    }
    public Double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Double sueldo) {
        this.sueldo = sueldo;
    }
    public String getDiadescanso() {
        return this.diadescanso;
    }
    
    public void setDiadescanso(String diadescanso) {
        this.diadescanso = diadescanso;
    }




}


